pull_request_rules:
  - name: Automatic PR merge
    conditions:
      - "#approved-reviews-by>=1"
      - check-success="Run Tests"
      - label!=do-not-merge
    actions:
      merge:
        method: squash
  - name: Auto-merge release bump
    conditions:
      - author=github-actions[bot]
      - head~=^bump-version-
      - title~=^Bump version after release
      - check-success~="Build, Check and Test"
      - check-success~="CodeQL Advanced / Analyze"
      - label!=do-not-merge
    actions:
      merge:
        method: squash
