site:
  title: tapik
urls:
  latest_version_segment: ''
  latest_version_segment_strategy: replace
content:
  edit_url: https://github.com/makiftutuncu/tapik/edit/{refname}/{path}
  sources:
    - url: .
      branches: HEAD
      tags: []
      start_path: docs
ui:
  bundle:
    url: ./site/target/antora-ui-bundle.zip
    snapshot: true
  supplemental_files: ./site/supplemental-ui
antora:
  extensions:
    - require: '@antora/collector-extension'
    - require: '@antora/lunr-extension'
      index_latest_only: true
output:
  clean: false
  dir: site/target/site
