<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.akif</groupId>
        <artifactId>tapik-parent</artifactId>
        <version>0.6.0</version>
    </parent>

    <artifactId>tapik-example-contract</artifactId>
    <name>tapik library example contract</name>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <!-- tag::contract-bom[] -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>dev.akif</groupId>
                <artifactId>tapik-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <!-- end::contract-bom[] -->

    <dependencies>
        <!-- tag::contract-dependencies[] -->
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-core</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-format-jackson</artifactId>
        </dependency>
        <!-- end::contract-dependencies[] -->
        <dependency>
            <groupId>io.kotest</groupId>
            <artifactId>kotest-runner-junit5-jvm</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.kotest</groupId>
            <artifactId>kotest-assertions-core-jvm</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- tag::compiler-plugin[] -->
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <configuration>
                    <compilerPlugins>
                        <plugin>tapik</plugin>
                    </compilerPlugins>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>dev.akif</groupId>
                        <artifactId>tapik-plugin-maven</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <!-- end::compiler-plugin[] -->
            <!-- tag::same-module-openapi[] -->
            <plugin>
                <groupId>dev.akif</groupId>
                <artifactId>tapik-plugin-maven</artifactId>
                <version>${project.version}</version>
                <executions>
                    <execution>
                        <id>generate-openapi</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <target>openapi</target>
                            <targetConfiguration>
                                <version>${project.version}</version>
                            </targetConfiguration>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- end::same-module-openapi[] -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
