<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.akif</groupId>
        <artifactId>tapik-parent</artifactId>
        <version>0.6.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>tapik-site</artifactId>
    <packaging>pom</packaging>
    <name>tapik website</name>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
        <maven.resources.version>3.4.0</maven.resources.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>dev.akif</groupId>
                <artifactId>tapik-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-core</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-common-format</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-common-plugin</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-common-spring</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-format-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-format-kotlinx</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-plugin-compiler</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-plugin-maven</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-target-openapi</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-target-spring-restclient</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.akif</groupId>
            <artifactId>tapik-target-spring-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-plugin-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.plugin-tools</groupId>
            <artifactId>maven-plugin-annotations</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${maven.resources.version}</version>
                <executions>
                    <execution>
                        <id>copy-website</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/site</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/src/main/resources</directory>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jetbrains.dokka</groupId>
                <artifactId>dokka-maven-plugin</artifactId>
                <version>${dokka.version}</version>
                <executions>
                    <execution>
                        <id>generate-unified-api-reference</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>dokka</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <moduleName>tapik</moduleName>
                    <outputDir>${project.build.directory}/site/docs/api</outputDir>
                    <jdkVersion>${jvm.version}</jdkVersion>
                    <suppressObviousFunctions>true</suppressObviousFunctions>
                    <suppressInheritedMembers>true</suppressInheritedMembers>
                    <includes>
                        <include>${project.basedir}/Module.md</include>
                    </includes>
                    <sourceDirectories>
                        <dir>${project.basedir}/../core/src/main/kotlin</dir>
                        <dir>${project.basedir}/../common-format/src/main/kotlin</dir>
                        <dir>${project.basedir}/../common-plugin/src/main/kotlin</dir>
                        <dir>${project.basedir}/../common-spring/src/main/kotlin</dir>
                        <dir>${project.basedir}/../format-jackson/src/main/kotlin</dir>
                        <dir>${project.basedir}/../format-kotlinx/src/main/kotlin</dir>
                        <dir>${project.basedir}/../plugin-compiler/src/main/kotlin</dir>
                        <dir>${project.basedir}/../plugin-maven/src/main/kotlin</dir>
                        <dir>${project.basedir}/../target-openapi/src/main/kotlin</dir>
                        <dir>${project.basedir}/../target-spring-restclient/src/main/kotlin</dir>
                        <dir>${project.basedir}/../target-spring-webmvc/src/main/kotlin</dir>
                    </sourceDirectories>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
